
package com.strongauth.skse.soapstubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SKSEServlet", targetNamespace = "http://sksews.strongauth.com/", wsdlLocation = "https://saka208.strongauth.com:8181/skse/SKSEServlet?wsdl")
public class SKSEServlet_Service
    extends Service
{

    private final static URL SKSESERVLET_WSDL_LOCATION;
    private final static WebServiceException SKSESERVLET_EXCEPTION;
    private final static QName SKSESERVLET_QNAME = new QName("http://sksews.strongauth.com/", "SKSEServlet");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://saka208.strongauth.com:8181/skse/SKSEServlet?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SKSESERVLET_WSDL_LOCATION = url;
        SKSESERVLET_EXCEPTION = e;
    }

    public SKSEServlet_Service() {
        super(__getWsdlLocation(), SKSESERVLET_QNAME);
    }

    public SKSEServlet_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SKSESERVLET_QNAME, features);
    }

    public SKSEServlet_Service(URL wsdlLocation) {
        super(wsdlLocation, SKSESERVLET_QNAME);
    }

    public SKSEServlet_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SKSESERVLET_QNAME, features);
    }

    public SKSEServlet_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SKSEServlet_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SKSEServlet
     */
    @WebEndpoint(name = "SKSEServletPort")
    public SKSEServlet getSKSEServletPort() {
        return super.getPort(new QName("http://sksews.strongauth.com/", "SKSEServletPort"), SKSEServlet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SKSEServlet
     */
    @WebEndpoint(name = "SKSEServletPort")
    public SKSEServlet getSKSEServletPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sksews.strongauth.com/", "SKSEServletPort"), SKSEServlet.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SKSESERVLET_EXCEPTION!= null) {
            throw SKSESERVLET_EXCEPTION;
        }
        return SKSESERVLET_WSDL_LOCATION;
    }

}
