
package com.strongauth.skce.ldap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LDAPEServlet", targetNamespace = "http://ldapews.strongauth.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LDAPEServlet {


    /**
     * 
     * @param svcinfo
     * @param password
     * @param username
     * @return
     *     returns com.strongauth.skce.ldap.SkceReturnObject
     * @throws SKCEException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.AuthenticateResponse")
    @Action(input = "http://ldapews.strongauth.com/LDAPEServlet/authenticateRequest", output = "http://ldapews.strongauth.com/LDAPEServlet/authenticateResponse", fault = {
        @FaultAction(className = SKCEException_Exception.class, value = "http://ldapews.strongauth.com/LDAPEServlet/authenticate/Fault/SKCEException")
    })
    public SkceReturnObject authenticate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws SKCEException_Exception
    ;

    /**
     * 
     * @param svcinfo
     * @param password
     * @param operation
     * @param username
     * @return
     *     returns com.strongauth.skce.ldap.SkceReturnObject
     * @throws SKCEException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorize", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.AuthorizeResponse")
    @Action(input = "http://ldapews.strongauth.com/LDAPEServlet/authorizeRequest", output = "http://ldapews.strongauth.com/LDAPEServlet/authorizeResponse", fault = {
        @FaultAction(className = SKCEException_Exception.class, value = "http://ldapews.strongauth.com/LDAPEServlet/authorize/Fault/SKCEException")
    })
    public SkceReturnObject authorize(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "operation", targetNamespace = "")
        String operation)
        throws SKCEException_Exception
    ;

    /**
     * 
     * @param svcinfo
     * @param password
     * @param username
     * @return
     *     returns com.strongauth.skce.ldap.SkceReturnObject
     * @throws SKCEException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adduser", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.Adduser")
    @ResponseWrapper(localName = "adduserResponse", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.AdduserResponse")
    @Action(input = "http://ldapews.strongauth.com/LDAPEServlet/adduserRequest", output = "http://ldapews.strongauth.com/LDAPEServlet/adduserResponse", fault = {
        @FaultAction(className = SKCEException_Exception.class, value = "http://ldapews.strongauth.com/LDAPEServlet/adduser/Fault/SKCEException")
    })
    public SkceReturnObject adduser(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws SKCEException_Exception
    ;

    /**
     * 
     * @param svcinfo
     * @param deletion
     * @param value
     * @param key
     * @param username
     * @return
     *     returns com.strongauth.skce.ldap.SkceReturnObject
     * @throws SKCEException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateuser", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.Updateuser")
    @ResponseWrapper(localName = "updateuserResponse", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.UpdateuserResponse")
    @Action(input = "http://ldapews.strongauth.com/LDAPEServlet/updateuserRequest", output = "http://ldapews.strongauth.com/LDAPEServlet/updateuserResponse", fault = {
        @FaultAction(className = SKCEException_Exception.class, value = "http://ldapews.strongauth.com/LDAPEServlet/updateuser/Fault/SKCEException")
    })
    public SkceReturnObject updateuser(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "value", targetNamespace = "")
        String value,
        @WebParam(name = "deletion", targetNamespace = "")
        boolean deletion)
        throws SKCEException_Exception
    ;

    /**
     * 
     * @param svcinfo
     * @param searchkey
     * @param basedn
     * @param searchvalue
     * @return
     *     returns com.strongauth.skce.ldap.SkceReturnObject
     * @throws SKCEException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getuserinfo", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.Getuserinfo")
    @ResponseWrapper(localName = "getuserinfoResponse", targetNamespace = "http://ldapews.strongauth.com/", className = "com.strongauth.skce.ldap.GetuserinfoResponse")
    @Action(input = "http://ldapews.strongauth.com/LDAPEServlet/getuserinfoRequest", output = "http://ldapews.strongauth.com/LDAPEServlet/getuserinfoResponse", fault = {
        @FaultAction(className = SKCEException_Exception.class, value = "http://ldapews.strongauth.com/LDAPEServlet/getuserinfo/Fault/SKCEException")
    })
    public SkceReturnObject getuserinfo(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "basedn", targetNamespace = "")
        String basedn,
        @WebParam(name = "searchkey", targetNamespace = "")
        String searchkey,
        @WebParam(name = "searchvalue", targetNamespace = "")
        String searchvalue)
        throws SKCEException_Exception
    ;

}
