#!/bin/sh
#
#   Startup/shutdown script for the OpenDJ Directory Service
#
#   Linux chkconfig stuff:
#
#   chkconfig: 345 70 40
#   description: OpenDJ Directory Service


# Source function library.
. /etc/init.d/functions

PROGRAMSTART="--user strongauth /usr/local/strongauth/OpenDJ-3.0.0/bin/start-ds"
PROGRAMSTOP="--user strongauth /usr/local/strongauth/OpenDJ-3.0.0/bin/stop-ds"

prog="OpenDJ 3.0.0 Directory Service"

start () {
	echo -n $"Starting $prog: "

	# start daemon
	daemon $PROGRAMSTART --quiet
        RETVAL=$?
	echo
	[ $RETVAL = 0 ] && touch /var/lock/subsys/OpenDJ
	return $RETVAL
}

stop () {
	# stop daemon
	echo -n $"Stopping $prog: "
	daemon $PROGRAMSTOP --quiet
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/OpenDJ
}

restart() {
	stop
	start
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	*)

	echo $"Usage: $prog {start|stop|restart}"
	exit 3
esac

exit $RETVAL
