/**
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License, as published by the Free Software Foundation and
 * available at http://www.fsf.org/licensing/licenses/lgpl.html,
 * version 2.1 or above.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2001-2018 StrongAuth, Inc.
 *
 * $Date$
 * $Revision$
 * $Author$
 * $URL$
 *
 * *********************************************
 *                    888
 *                    888
 *                    888
 *  88888b.   .d88b.  888888  .d88b.  .d8888b
 *  888 "88b d88""88b 888    d8P  Y8b 88K
 *  888  888 888  888 888    88888888 "Y8888b.
 *  888  888 Y88..88P Y88b.  Y8b.          X88
 *  888  888  "Y88P"   "Y888  "Y8888   88888P'
 *
 * *********************************************
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 04:16:45 PM PDT 
//


package com.strongauth.skse.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Projects">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Project" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prjid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TRSMs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TRSM" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trsmid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="trsmname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="trsmtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Slots" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="slotid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="slotpassworddid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="slotpasswordtoken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Profiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Profile" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="kpid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="keysize" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="algorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Domains">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Domain" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="domaintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projects",
    "trsMs",
    "profiles",
    "domains"
})
@XmlRootElement(name = "getInfoResponse")
public class GetInfoResponse {

    @XmlElement(name = "Projects", required = true)
    protected GetInfoResponse.Projects projects;
    @XmlElement(name = "TRSMs", required = true)
    protected GetInfoResponse.TRSMs trsMs;
    @XmlElement(name = "Profiles", required = true)
    protected GetInfoResponse.Profiles profiles;
    @XmlElement(name = "Domains", required = true)
    protected GetInfoResponse.Domains domains;

    /**
     * Gets the value of the projects property.
     * 
     * @return
     *     possible object is
     *     {@link GetInfoResponse.Projects }
     *     
     */
    public GetInfoResponse.Projects getProjects() {
        return projects;
    }

    /**
     * Sets the value of the projects property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetInfoResponse.Projects }
     *     
     */
    public void setProjects(GetInfoResponse.Projects value) {
        this.projects = value;
    }

    /**
     * Gets the value of the trsMs property.
     * 
     * @return
     *     possible object is
     *     {@link GetInfoResponse.TRSMs }
     *     
     */
    public GetInfoResponse.TRSMs getTRSMs() {
        return trsMs;
    }

    /**
     * Sets the value of the trsMs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetInfoResponse.TRSMs }
     *     
     */
    public void setTRSMs(GetInfoResponse.TRSMs value) {
        this.trsMs = value;
    }

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link GetInfoResponse.Profiles }
     *     
     */
    public GetInfoResponse.Profiles getProfiles() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetInfoResponse.Profiles }
     *     
     */
    public void setProfiles(GetInfoResponse.Profiles value) {
        this.profiles = value;
    }

    /**
     * Gets the value of the domains property.
     * 
     * @return
     *     possible object is
     *     {@link GetInfoResponse.Domains }
     *     
     */
    public GetInfoResponse.Domains getDomains() {
        return domains;
    }

    /**
     * Sets the value of the domains property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetInfoResponse.Domains }
     *     
     */
    public void setDomains(GetInfoResponse.Domains value) {
        this.domains = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Domain" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="domaintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domain"
    })
    public static class Domains {

        @XmlElement(name = "Domain")
        protected List<GetInfoResponse.Domains.Domain> domain;

        /**
         * Gets the value of the domain property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the domain property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDomain().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetInfoResponse.Domains.Domain }
         * 
         * 
         */
        public List<GetInfoResponse.Domains.Domain> getDomain() {
            if (domain == null) {
                domain = new ArrayList<GetInfoResponse.Domains.Domain>();
            }
            return this.domain;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="domaintype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "did",
            "name",
            "domaintype",
            "status"
        })
        public static class Domain {

            protected long did;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String domaintype;
            @XmlElement(required = true)
            protected String status;

            /**
             * Gets the value of the did property.
             * 
             */
            public long getDid() {
                return did;
            }

            /**
             * Sets the value of the did property.
             * 
             */
            public void setDid(long value) {
                this.did = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the domaintype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDomaintype() {
                return domaintype;
            }

            /**
             * Sets the value of the domaintype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDomaintype(String value) {
                this.domaintype = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Profile" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="kpid" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="keysize" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="algorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "profile"
    })
    public static class Profiles {

        @XmlElement(name = "Profile")
        protected List<GetInfoResponse.Profiles.Profile> profile;

        /**
         * Gets the value of the profile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the profile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetInfoResponse.Profiles.Profile }
         * 
         * 
         */
        public List<GetInfoResponse.Profiles.Profile> getProfile() {
            if (profile == null) {
                profile = new ArrayList<GetInfoResponse.Profiles.Profile>();
            }
            return this.profile;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="kpid" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="keysize" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="algorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "did",
            "kpid",
            "name",
            "keysize",
            "description",
            "algorithm",
            "validity",
            "status"
        })
        public static class Profile {

            protected long did;
            protected long kpid;
            @XmlElement(required = true)
            protected String name;
            protected long keysize;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String algorithm;
            protected long validity;
            @XmlElement(required = true)
            protected String status;

            /**
             * Gets the value of the did property.
             * 
             */
            public long getDid() {
                return did;
            }

            /**
             * Sets the value of the did property.
             * 
             */
            public void setDid(long value) {
                this.did = value;
            }

            /**
             * Gets the value of the kpid property.
             * 
             */
            public long getKpid() {
                return kpid;
            }

            /**
             * Sets the value of the kpid property.
             * 
             */
            public void setKpid(long value) {
                this.kpid = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the keysize property.
             * 
             */
            public long getKeysize() {
                return keysize;
            }

            /**
             * Sets the value of the keysize property.
             * 
             */
            public void setKeysize(long value) {
                this.keysize = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the algorithm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAlgorithm() {
                return algorithm;
            }

            /**
             * Sets the value of the algorithm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAlgorithm(String value) {
                this.algorithm = value;
            }

            /**
             * Gets the value of the validity property.
             * 
             */
            public long getValidity() {
                return validity;
            }

            /**
             * Sets the value of the validity property.
             * 
             */
            public void setValidity(long value) {
                this.validity = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Project" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prjid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "project"
    })
    public static class Projects {

        @XmlElement(name = "Project")
        protected List<GetInfoResponse.Projects.Project> project;

        /**
         * Gets the value of the project property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the project property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetInfoResponse.Projects.Project }
         * 
         * 
         */
        public List<GetInfoResponse.Projects.Project> getProject() {
            if (project == null) {
                project = new ArrayList<GetInfoResponse.Projects.Project>();
            }
            return this.project;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prjid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "did",
            "prjid",
            "name"
        })
        public static class Project {

            @XmlElement(required = true)
            protected String did;
            @XmlElement(required = true)
            protected String prjid;
            @XmlElement(required = true)
            protected String name;

            /**
             * Gets the value of the did property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDid() {
                return did;
            }

            /**
             * Sets the value of the did property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDid(String value) {
                this.did = value;
            }

            /**
             * Gets the value of the prjid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrjid() {
                return prjid;
            }

            /**
             * Sets the value of the prjid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrjid(String value) {
                this.prjid = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TRSM" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trsmid" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="trsmname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="trsmtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Slots" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="slotid" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="slotpassworddid" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="slotpasswordtoken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trsm"
    })
    public static class TRSMs {

        @XmlElement(name = "TRSM")
        protected List<GetInfoResponse.TRSMs.TRSM> trsm;

        /**
         * Gets the value of the trsm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the trsm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTRSM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetInfoResponse.TRSMs.TRSM }
         * 
         * 
         */
        public List<GetInfoResponse.TRSMs.TRSM> getTRSM() {
            if (trsm == null) {
                trsm = new ArrayList<GetInfoResponse.TRSMs.TRSM>();
            }
            return this.trsm;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="trsmid" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="trsmname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="trsmtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Slots" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="slotid" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="slotpassworddid" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="slotpasswordtoken" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trsmid",
            "trsmname",
            "trsmtype",
            "slots"
        })
        public static class TRSM {

            protected long trsmid;
            @XmlElement(required = true)
            protected String trsmname;
            @XmlElement(required = true)
            protected String trsmtype;
            @XmlElement(name = "Slots")
            protected List<GetInfoResponse.TRSMs.TRSM.Slots> slots;

            /**
             * Gets the value of the trsmid property.
             * 
             */
            public long getTrsmid() {
                return trsmid;
            }

            /**
             * Sets the value of the trsmid property.
             * 
             */
            public void setTrsmid(long value) {
                this.trsmid = value;
            }

            /**
             * Gets the value of the trsmname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTrsmname() {
                return trsmname;
            }

            /**
             * Sets the value of the trsmname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTrsmname(String value) {
                this.trsmname = value;
            }

            /**
             * Gets the value of the trsmtype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTrsmtype() {
                return trsmtype;
            }

            /**
             * Sets the value of the trsmtype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTrsmtype(String value) {
                this.trsmtype = value;
            }

            /**
             * Gets the value of the slots property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the slots property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSlots().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GetInfoResponse.TRSMs.TRSM.Slots }
             * 
             * 
             */
            public List<GetInfoResponse.TRSMs.TRSM.Slots> getSlots() {
                if (slots == null) {
                    slots = new ArrayList<GetInfoResponse.TRSMs.TRSM.Slots>();
                }
                return this.slots;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="slotid" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="slotpassworddid" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="slotpasswordtoken" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "slotid",
                "slotpassworddid",
                "slotpasswordtoken"
            })
            public static class Slots {

                protected long slotid;
                protected long slotpassworddid;
                @XmlElement(required = true)
                protected String slotpasswordtoken;

                /**
                 * Gets the value of the slotid property.
                 * 
                 */
                public long getSlotid() {
                    return slotid;
                }

                /**
                 * Sets the value of the slotid property.
                 * 
                 */
                public void setSlotid(long value) {
                    this.slotid = value;
                }

                /**
                 * Gets the value of the slotpassworddid property.
                 * 
                 */
                public long getSlotpassworddid() {
                    return slotpassworddid;
                }

                /**
                 * Sets the value of the slotpassworddid property.
                 * 
                 */
                public void setSlotpassworddid(long value) {
                    this.slotpassworddid = value;
                }

                /**
                 * Gets the value of the slotpasswordtoken property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSlotpasswordtoken() {
                    return slotpasswordtoken;
                }

                /**
                 * Sets the value of the slotpasswordtoken property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSlotpasswordtoken(String value) {
                    this.slotpasswordtoken = value;
                }

            }

        }

    }

}
