/**
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License, as published by the Free Software Foundation and
 * available at http://www.fsf.org/licensing/licenses/lgpl.html,
 * version 2.1 or above.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2001-2018 StrongAuth, Inc.
 *
 * $Date$
 * $Revision$
 * $Author$
 * $URL$
 *
 * *********************************************
 *                    888
 *                    888
 *                    888
 *  88888b.   .d88b.  888888  .d88b.  .d8888b
 *  888 "88b d88""88b 888    d8P  Y8b 88K
 *  888  888 888  888 888    88888888 "Y8888b.
 *  888  888 Y88..88P Y88b.  Y8b.          X88
 *  888  888  "Y88P"   "Y888  "Y8888   88888P'
 *
 * *********************************************
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 04:16:45 PM PDT 
//


package com.strongauth.skse.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Domains" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="Keys" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="keyid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="projectid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="certid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="kpid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="krmid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="trsmid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="profilename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="cn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="serialnbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="subjectdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="issuerdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="cert_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="signature_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="eecert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="KeyDetails" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="keydetailid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                                       &lt;element name="requester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="create_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="modify_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Users" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="isGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                                       &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domains"
})
@XmlRootElement(name = "listKeysResponse")
public class ListKeysResponse {

    @XmlElement(name = "Domains")
    protected List<ListKeysResponse.Domains> domains;

    /**
     * Gets the value of the domains property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domains property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomains().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListKeysResponse.Domains }
     * 
     * 
     */
    public List<ListKeysResponse.Domains> getDomains() {
        if (domains == null) {
            domains = new ArrayList<ListKeysResponse.Domains>();
        }
        return this.domains;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="did" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="Keys" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="keyid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="projectid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="certid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="kpid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="krmid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="trsmid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="profilename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="cn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="serialnbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="subjectdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="issuerdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="cert_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="signature_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="eecert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="KeyDetails" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="keydetailid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                             &lt;element name="requester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="create_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="modify_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Users" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="isGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                             &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "did",
        "keys"
    })
    public static class Domains {

        protected Long did;
        @XmlElement(name = "Keys")
        protected List<ListKeysResponse.Domains.Keys> keys;

        /**
         * Gets the value of the did property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getDid() {
            return did;
        }

        /**
         * Sets the value of the did property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setDid(Long value) {
            this.did = value;
        }

        /**
         * Gets the value of the keys property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the keys property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKeys().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ListKeysResponse.Domains.Keys }
         * 
         * 
         */
        public List<ListKeysResponse.Domains.Keys> getKeys() {
            if (keys == null) {
                keys = new ArrayList<ListKeysResponse.Domains.Keys>();
            }
            return this.keys;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="keyid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="projectid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="certid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="kpid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="krmid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="validity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="trsmid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="profilename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="cn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="serialnbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="subjectdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="issuerdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="cert_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="signature_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="eecert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="KeyDetails" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="keydetailid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *                   &lt;element name="requester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="create_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="modify_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Users" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="isGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *                   &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "keyid",
            "projectid",
            "certid",
            "kpid",
            "krmid",
            "alias",
            "validity",
            "trsmid",
            "profilename",
            "cn",
            "serialnbr",
            "subjectdn",
            "issuerdn",
            "startDate",
            "endDate",
            "certType",
            "signatureType",
            "signature",
            "eecert",
            "keyDetails",
            "users"
        })
        public static class Keys {

            protected Long keyid;
            protected Long projectid;
            protected Long certid;
            protected Long kpid;
            protected Long krmid;
            protected String alias;
            protected Long validity;
            protected Long trsmid;
            protected String profilename;
            protected String cn;
            protected String serialnbr;
            protected String subjectdn;
            protected String issuerdn;
            @XmlElement(name = "start_date")
            protected String startDate;
            @XmlElement(name = "end_date")
            protected String endDate;
            @XmlElement(name = "cert_type")
            protected String certType;
            @XmlElement(name = "signature_type")
            protected String signatureType;
            protected String signature;
            protected String eecert;
            @XmlElement(name = "KeyDetails")
            protected List<ListKeysResponse.Domains.Keys.KeyDetails> keyDetails;
            @XmlElement(name = "Users")
            protected List<ListKeysResponse.Domains.Keys.Users> users;

            /**
             * Gets the value of the keyid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getKeyid() {
                return keyid;
            }

            /**
             * Sets the value of the keyid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setKeyid(Long value) {
                this.keyid = value;
            }

            /**
             * Gets the value of the projectid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getProjectid() {
                return projectid;
            }

            /**
             * Sets the value of the projectid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setProjectid(Long value) {
                this.projectid = value;
            }

            /**
             * Gets the value of the certid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getCertid() {
                return certid;
            }

            /**
             * Sets the value of the certid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setCertid(Long value) {
                this.certid = value;
            }

            /**
             * Gets the value of the kpid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getKpid() {
                return kpid;
            }

            /**
             * Sets the value of the kpid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setKpid(Long value) {
                this.kpid = value;
            }

            /**
             * Gets the value of the krmid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getKrmid() {
                return krmid;
            }

            /**
             * Sets the value of the krmid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setKrmid(Long value) {
                this.krmid = value;
            }

            /**
             * Gets the value of the alias property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAlias() {
                return alias;
            }

            /**
             * Sets the value of the alias property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAlias(String value) {
                this.alias = value;
            }

            /**
             * Gets the value of the validity property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getValidity() {
                return validity;
            }

            /**
             * Sets the value of the validity property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setValidity(Long value) {
                this.validity = value;
            }

            /**
             * Gets the value of the trsmid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTrsmid() {
                return trsmid;
            }

            /**
             * Sets the value of the trsmid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTrsmid(Long value) {
                this.trsmid = value;
            }

            /**
             * Gets the value of the profilename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProfilename() {
                return profilename;
            }

            /**
             * Sets the value of the profilename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProfilename(String value) {
                this.profilename = value;
            }

            /**
             * Gets the value of the cn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCn() {
                return cn;
            }

            /**
             * Sets the value of the cn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCn(String value) {
                this.cn = value;
            }

            /**
             * Gets the value of the serialnbr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerialnbr() {
                return serialnbr;
            }

            /**
             * Sets the value of the serialnbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerialnbr(String value) {
                this.serialnbr = value;
            }

            /**
             * Gets the value of the subjectdn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubjectdn() {
                return subjectdn;
            }

            /**
             * Sets the value of the subjectdn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubjectdn(String value) {
                this.subjectdn = value;
            }

            /**
             * Gets the value of the issuerdn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIssuerdn() {
                return issuerdn;
            }

            /**
             * Sets the value of the issuerdn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIssuerdn(String value) {
                this.issuerdn = value;
            }

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartDate(String value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndDate(String value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the certType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCertType() {
                return certType;
            }

            /**
             * Sets the value of the certType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCertType(String value) {
                this.certType = value;
            }

            /**
             * Gets the value of the signatureType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSignatureType() {
                return signatureType;
            }

            /**
             * Sets the value of the signatureType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSignatureType(String value) {
                this.signatureType = value;
            }

            /**
             * Gets the value of the signature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSignature() {
                return signature;
            }

            /**
             * Sets the value of the signature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSignature(String value) {
                this.signature = value;
            }

            /**
             * Gets the value of the eecert property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEecert() {
                return eecert;
            }

            /**
             * Sets the value of the eecert property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEecert(String value) {
                this.eecert = value;
            }

            /**
             * Gets the value of the keyDetails property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the keyDetails property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKeyDetails().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ListKeysResponse.Domains.Keys.KeyDetails }
             * 
             * 
             */
            public List<ListKeysResponse.Domains.Keys.KeyDetails> getKeyDetails() {
                if (keyDetails == null) {
                    keyDetails = new ArrayList<ListKeysResponse.Domains.Keys.KeyDetails>();
                }
                return this.keyDetails;
            }

            /**
             * Gets the value of the users property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the users property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUsers().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ListKeysResponse.Domains.Keys.Users }
             * 
             * 
             */
            public List<ListKeysResponse.Domains.Keys.Users> getUsers() {
                if (users == null) {
                    users = new ArrayList<ListKeysResponse.Domains.Keys.Users>();
                }
                return this.users;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="keydetailid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
             *         &lt;element name="requester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="create_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="modify_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "keydetailid",
                "requester",
                "createDate",
                "modifyDate",
                "status",
                "notes"
            })
            public static class KeyDetails {

                protected Long keydetailid;
                protected String requester;
                @XmlElement(name = "create_date")
                protected String createDate;
                @XmlElement(name = "modify_date")
                protected String modifyDate;
                protected String status;
                protected String notes;

                /**
                 * Gets the value of the keydetailid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                public Long getKeydetailid() {
                    return keydetailid;
                }

                /**
                 * Sets the value of the keydetailid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setKeydetailid(Long value) {
                    this.keydetailid = value;
                }

                /**
                 * Gets the value of the requester property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequester() {
                    return requester;
                }

                /**
                 * Sets the value of the requester property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequester(String value) {
                    this.requester = value;
                }

                /**
                 * Gets the value of the createDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCreateDate() {
                    return createDate;
                }

                /**
                 * Sets the value of the createDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCreateDate(String value) {
                    this.createDate = value;
                }

                /**
                 * Gets the value of the modifyDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModifyDate() {
                    return modifyDate;
                }

                /**
                 * Sets the value of the modifyDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModifyDate(String value) {
                    this.modifyDate = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the notes property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNotes() {
                    return notes;
                }

                /**
                 * Sets the value of the notes property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNotes(String value) {
                    this.notes = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="isGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
             *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "isGroup",
                "target"
            })
            public static class Users {

                protected Boolean isGroup;
                protected String target;

                /**
                 * Gets the value of the isGroup property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isIsGroup() {
                    return isGroup;
                }

                /**
                 * Sets the value of the isGroup property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setIsGroup(Boolean value) {
                    this.isGroup = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

            }

        }

    }

}
