/**
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License, as published by the Free Software Foundation and
 * available at http://www.fsf.org/licensing/licenses/lgpl.html,
 * version 2.1 or above.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2001-2018 StrongAuth, Inc.
 *
 * $Date$
 * $Revision$
 * $Author$
 * $URL$
 *
 * *********************************************
 *                    888
 *                    888
 *                    888
 *  88888b.   .d88b.  888888  .d88b.  .d8888b
 *  888 "88b d88""88b 888    d8P  Y8b 88K
 *  888  888 888  888 888    88888888 "Y8888b.
 *  888  888 Y88..88P Y88b.  Y8b.          X88
 *  888  888  "Y88P"   "Y888  "Y8888   88888P'
 *
 * *********************************************
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 04:16:45 PM PDT 
//


package com.strongauth.skse.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.strongauth.skse.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.strongauth.skse.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListKeyRequestsResponse }
     * 
     */
    public ListKeyRequestsResponse createListKeyRequestsResponse() {
        return new ListKeyRequestsResponse();
    }

    /**
     * Create an instance of {@link SKCEInput }
     * 
     */
    public SKCEInput createSKCEInput() {
        return new SKCEInput();
    }

    /**
     * Create an instance of {@link GetInfoResponse }
     * 
     */
    public GetInfoResponse createGetInfoResponse() {
        return new GetInfoResponse();
    }

    /**
     * Create an instance of {@link ListKeysResponse }
     * 
     */
    public ListKeysResponse createListKeysResponse() {
        return new ListKeysResponse();
    }

    /**
     * Create an instance of {@link ListKeysResponse.Domains }
     * 
     */
    public ListKeysResponse.Domains createListKeysResponseDomains() {
        return new ListKeysResponse.Domains();
    }

    /**
     * Create an instance of {@link ListKeysResponse.Domains.Keys }
     * 
     */
    public ListKeysResponse.Domains.Keys createListKeysResponseDomainsKeys() {
        return new ListKeysResponse.Domains.Keys();
    }

    /**
     * Create an instance of {@link GetInfoResponse.Domains }
     * 
     */
    public GetInfoResponse.Domains createGetInfoResponseDomains() {
        return new GetInfoResponse.Domains();
    }

    /**
     * Create an instance of {@link GetInfoResponse.Profiles }
     * 
     */
    public GetInfoResponse.Profiles createGetInfoResponseProfiles() {
        return new GetInfoResponse.Profiles();
    }

    /**
     * Create an instance of {@link GetInfoResponse.TRSMs }
     * 
     */
    public GetInfoResponse.TRSMs createGetInfoResponseTRSMs() {
        return new GetInfoResponse.TRSMs();
    }

    /**
     * Create an instance of {@link GetInfoResponse.TRSMs.TRSM }
     * 
     */
    public GetInfoResponse.TRSMs.TRSM createGetInfoResponseTRSMsTRSM() {
        return new GetInfoResponse.TRSMs.TRSM();
    }

    /**
     * Create an instance of {@link GetInfoResponse.Projects }
     * 
     */
    public GetInfoResponse.Projects createGetInfoResponseProjects() {
        return new GetInfoResponse.Projects();
    }

    /**
     * Create an instance of {@link ListKeyRequestsResponse.Domains }
     * 
     */
    public ListKeyRequestsResponse.Domains createListKeyRequestsResponseDomains() {
        return new ListKeyRequestsResponse.Domains();
    }

    /**
     * Create an instance of {@link ListKeyRequestsResponse.Domains.KeyRequestMaster }
     * 
     */
    public ListKeyRequestsResponse.Domains.KeyRequestMaster createListKeyRequestsResponseDomainsKeyRequestMaster() {
        return new ListKeyRequestsResponse.Domains.KeyRequestMaster();
    }

    /**
     * Create an instance of {@link SKCEInput.SAKA }
     * 
     */
    public SKCEInput.SAKA createSKCEInputSAKA() {
        return new SKCEInput.SAKA();
    }

    /**
     * Create an instance of {@link SKCEInput.TRSM }
     * 
     */
    public SKCEInput.TRSM createSKCEInputTRSM() {
        return new SKCEInput.TRSM();
    }

    /**
     * Create an instance of {@link SKCEInput.P12 }
     * 
     */
    public SKCEInput.P12 createSKCEInputP12() {
        return new SKCEInput.P12();
    }

    /**
     * Create an instance of {@link ListKeysResponse.Domains.Keys.KeyDetails }
     * 
     */
    public ListKeysResponse.Domains.Keys.KeyDetails createListKeysResponseDomainsKeysKeyDetails() {
        return new ListKeysResponse.Domains.Keys.KeyDetails();
    }

    /**
     * Create an instance of {@link ListKeysResponse.Domains.Keys.Users }
     * 
     */
    public ListKeysResponse.Domains.Keys.Users createListKeysResponseDomainsKeysUsers() {
        return new ListKeysResponse.Domains.Keys.Users();
    }

    /**
     * Create an instance of {@link GetInfoResponse.Domains.Domain }
     * 
     */
    public GetInfoResponse.Domains.Domain createGetInfoResponseDomainsDomain() {
        return new GetInfoResponse.Domains.Domain();
    }

    /**
     * Create an instance of {@link GetInfoResponse.Profiles.Profile }
     * 
     */
    public GetInfoResponse.Profiles.Profile createGetInfoResponseProfilesProfile() {
        return new GetInfoResponse.Profiles.Profile();
    }

    /**
     * Create an instance of {@link GetInfoResponse.TRSMs.TRSM.Slots }
     * 
     */
    public GetInfoResponse.TRSMs.TRSM.Slots createGetInfoResponseTRSMsTRSMSlots() {
        return new GetInfoResponse.TRSMs.TRSM.Slots();
    }

    /**
     * Create an instance of {@link GetInfoResponse.Projects.Project }
     * 
     */
    public GetInfoResponse.Projects.Project createGetInfoResponseProjectsProject() {
        return new GetInfoResponse.Projects.Project();
    }

    /**
     * Create an instance of {@link ListKeyRequestsResponse.Domains.KeyRequestMaster.KeyRequestDetail }
     * 
     */
    public ListKeyRequestsResponse.Domains.KeyRequestMaster.KeyRequestDetail createListKeyRequestsResponseDomainsKeyRequestMasterKeyRequestDetail() {
        return new ListKeyRequestsResponse.Domains.KeyRequestMaster.KeyRequestDetail();
    }

}
