/**
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License, as published by the Free Software Foundation and
 * available at http://www.fsf.org/licensing/licenses/lgpl.html,
 * version 2.1 or above.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2001-2018 StrongAuth, Inc.
 *
 * $Date$
 * $Revision$
 * $Author$
 * $URL$
 *
 * *********************************************
 *                    888
 *                    888
 *                    888
 *  88888b.   .d88b.  888888  .d88b.  .d8888b
 *  888 "88b d88""88b 888    d8P  Y8b 88K
 *  888  888 888  888 888    88888888 "Y8888b.
 *  888  888 Y88..88P Y88b.  Y8b.          X88
 *  888  888  "Y88P"   "Y888  "Y8888   88888P'
 *
 * *********************************************
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 04:16:45 PM PDT 
//


package com.strongauth.skse.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SAKA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TRSM">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="trsmdevice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="trsmslotid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="trsmslotdid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="trsmslotpasswordtoken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="P12">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="p12did" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="p12token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p12passworddid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="p12passwordtoken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p12alias" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saka",
    "trsm",
    "p12"
})
@XmlRootElement(name = "SKCEInput")
public class SKCEInput {

    @XmlElement(name = "SAKA", required = true)
    protected SKCEInput.SAKA saka;
    @XmlElement(name = "TRSM", required = true)
    protected SKCEInput.TRSM trsm;
    @XmlElement(name = "P12", required = true)
    protected SKCEInput.P12 p12;

    /**
     * Gets the value of the saka property.
     * 
     * @return
     *     possible object is
     *     {@link SKCEInput.SAKA }
     *     
     */
    public SKCEInput.SAKA getSAKA() {
        return saka;
    }

    /**
     * Sets the value of the saka property.
     * 
     * @param value
     *     allowed object is
     *     {@link SKCEInput.SAKA }
     *     
     */
    public void setSAKA(SKCEInput.SAKA value) {
        this.saka = value;
    }

    /**
     * Gets the value of the trsm property.
     * 
     * @return
     *     possible object is
     *     {@link SKCEInput.TRSM }
     *     
     */
    public SKCEInput.TRSM getTRSM() {
        return trsm;
    }

    /**
     * Sets the value of the trsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SKCEInput.TRSM }
     *     
     */
    public void setTRSM(SKCEInput.TRSM value) {
        this.trsm = value;
    }

    /**
     * Gets the value of the p12 property.
     * 
     * @return
     *     possible object is
     *     {@link SKCEInput.P12 }
     *     
     */
    public SKCEInput.P12 getP12() {
        return p12;
    }

    /**
     * Sets the value of the p12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SKCEInput.P12 }
     *     
     */
    public void setP12(SKCEInput.P12 value) {
        this.p12 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="p12did" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="p12token" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="p12passworddid" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="p12passwordtoken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="p12alias" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p12Did",
        "p12Token",
        "p12Passworddid",
        "p12Passwordtoken",
        "p12Alias"
    })
    public static class P12 {

        @XmlElement(name = "p12did")
        protected long p12Did;
        @XmlElement(name = "p12token", required = true)
        protected String p12Token;
        @XmlElement(name = "p12passworddid")
        protected long p12Passworddid;
        @XmlElement(name = "p12passwordtoken", required = true)
        protected String p12Passwordtoken;
        @XmlElement(name = "p12alias", required = true)
        protected String p12Alias;

        /**
         * Gets the value of the p12Did property.
         * 
         */
        public long getP12Did() {
            return p12Did;
        }

        /**
         * Sets the value of the p12Did property.
         * 
         */
        public void setP12Did(long value) {
            this.p12Did = value;
        }

        /**
         * Gets the value of the p12Token property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP12Token() {
            return p12Token;
        }

        /**
         * Sets the value of the p12Token property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP12Token(String value) {
            this.p12Token = value;
        }

        /**
         * Gets the value of the p12Passworddid property.
         * 
         */
        public long getP12Passworddid() {
            return p12Passworddid;
        }

        /**
         * Sets the value of the p12Passworddid property.
         * 
         */
        public void setP12Passworddid(long value) {
            this.p12Passworddid = value;
        }

        /**
         * Gets the value of the p12Passwordtoken property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP12Passwordtoken() {
            return p12Passwordtoken;
        }

        /**
         * Sets the value of the p12Passwordtoken property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP12Passwordtoken(String value) {
            this.p12Passwordtoken = value;
        }

        /**
         * Gets the value of the p12Alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP12Alias() {
            return p12Alias;
        }

        /**
         * Sets the value of the p12Alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP12Alias(String value) {
            this.p12Alias = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "url",
        "username",
        "password"
    })
    public static class SAKA {

        @XmlElement(required = true)
        protected String url;
        @XmlElement(required = true)
        protected String username;
        @XmlElement(required = true)
        protected String password;

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="trsmdevice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="trsmslotid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="trsmslotdid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="trsmslotpasswordtoken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trsmdevice",
        "trsmslotid",
        "trsmslotdid",
        "trsmslotpasswordtoken"
    })
    public static class TRSM {

        protected String trsmdevice;
        protected Long trsmslotid;
        protected Long trsmslotdid;
        protected String trsmslotpasswordtoken;

        /**
         * Gets the value of the trsmdevice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrsmdevice() {
            return trsmdevice;
        }

        /**
         * Sets the value of the trsmdevice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrsmdevice(String value) {
            this.trsmdevice = value;
        }

        /**
         * Gets the value of the trsmslotid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTrsmslotid() {
            return trsmslotid;
        }

        /**
         * Sets the value of the trsmslotid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTrsmslotid(Long value) {
            this.trsmslotid = value;
        }

        /**
         * Gets the value of the trsmslotdid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTrsmslotdid() {
            return trsmslotdid;
        }

        /**
         * Sets the value of the trsmslotdid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTrsmslotdid(Long value) {
            this.trsmslotdid = value;
        }

        /**
         * Gets the value of the trsmslotpasswordtoken property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrsmslotpasswordtoken() {
            return trsmslotpasswordtoken;
        }

        /**
         * Sets the value of the trsmslotpasswordtoken property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrsmslotpasswordtoken(String value) {
            this.trsmslotpasswordtoken = value;
        }

    }

}
