
package com.strongauth.skfe.soapstubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SKFEServlet", targetNamespace = "http://soap.u2f.skfews.strongauth.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SKFEServlet {


    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.AuthenticateResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/authenticateRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/authenticateResponse")
    public String authenticate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getserverinfo", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Getserverinfo")
    @ResponseWrapper(localName = "getserverinfoResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.GetserverinfoResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/getserverinfoRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/getserverinfoResponse")
    public String getserverinfo(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preauthenticate", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Preauthenticate")
    @ResponseWrapper(localName = "preauthenticateResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.PreauthenticateResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/preauthenticateRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/preauthenticateResponse")
    public String preauthenticate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preauthorize", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Preauthorize")
    @ResponseWrapper(localName = "preauthorizeResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.PreauthorizeResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/preauthorizeRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/preauthorizeResponse")
    public String preauthorize(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deactivate", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Deactivate")
    @ResponseWrapper(localName = "deactivateResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.DeactivateResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/deactivateRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/deactivateResponse")
    public String deactivate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getkeysinfo", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Getkeysinfo")
    @ResponseWrapper(localName = "getkeysinfoResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.GetkeysinfoResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/getkeysinfoRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/getkeysinfoResponse")
    public String getkeysinfo(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preregister", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Preregister")
    @ResponseWrapper(localName = "preregisterResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.PreregisterResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/preregisterRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/preregisterResponse")
    public String preregister(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorize", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.AuthorizeResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/authorizeRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/authorizeResponse")
    public String authorize(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deregister", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Deregister")
    @ResponseWrapper(localName = "deregisterResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.DeregisterResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/deregisterRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/deregisterResponse")
    public String deregister(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activate", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Activate")
    @ResponseWrapper(localName = "activateResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.ActivateResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/activateRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/activateResponse")
    public String activate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", className = "com.strongauth.skfe.soapstubs.RegisterResponse")
    @Action(input = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/registerRequest", output = "http://soap.u2f.skfews.strongauth.com/SKFEServlet/registerResponse")
    public String register(
        @WebParam(name = "svcinfo", targetNamespace = "")
        SKCEServiceInfoType svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

}
